printWidth: 110
singleQuote: true
jsxSingleQuote: true
useTabs: false
semi: false
trailingComma: es5
plugins:
  - '@trivago/prettier-plugin-sort-imports'
  - '@prettier/plugin-xml'
  - tailwindcss
  - prettier-plugin-tailwindcss

xmlSelfClosingSpace: true
xmlSortAttributesByKey: true

importOrderSeparation: true
importOrderSortSpecifiers: true
importOrder:
  - .+\.css$
  - <THIRD_PARTY_MODULES>
  - ^[~]
  - ^[./]

tailwindStylesheet: ./src/styles/tailwind.css
tailwindFunctions:
  - clsx

overrides:
  - files:
      - .*rc
      - '*.json'
      - .*.json
    options:
      parser: json
      tabWidth: 2
